### ISSUE TITLE
This addon seems to be breaking runloop behavior in tests.

### ISSUE THREAD

**Issue by runspired** [runspired/ember-run-raf#2]
Work has begun to cleanup the `install` mechanism to prevent this, and to add a full test suite to guard against this regression in the future.

**Comment by knownasilya** [comment]
Also encountered something similar, but not tests specifically, but running our app in PhantomJS.

Using v1.0.5

**Comment by runspired** [comment]
Explain what you mean by "not tests specifically", this addon is meant to change how the run loop operates (see the README), this issue is because it was (in Phantom) breaking all tests.  On the latest build this seems to be fixed in my test apps but would like more information if it's still failing elsewhere.

**Comment by knownasilya** [comment]
We run our app in phantomjs for advanced PDF printing, @ismyrnow can you chime in on the errors you were seeing?

**Comment by ismyrnow** [comment]
After digging deeper, I opened a PR (#3) with a fix.

Basically, the code path that browsers without `requestAnimationFrame` used had a bug in it.
