### ISSUE TITLE
Ember.run.debounce does not work properly

### ISSUE THREAD

**Issue by bekzod** [runspired/ember-run-raf#6]
`Ember.run.debounce` calls function immediately so it does not debounce at all

ember: 2.5.1
ember-run-raf: 1.1.1

**Comment by tschoartschi** [comment]
Same problem here. We also use

ember: 2.5.1 and 
ember-run-raf: 1.1.1

@bekzod: do you know a workaround?

**Comment by FilmKnurd** [comment]
Also ran into this. Debounce just doesn't debounce anymore :-(

**Comment by mohtada-h** [comment]
Same problem here. I also use:
ember: 2.5.1
ember-run-raf: 1.1.1

**Comment by runspired** [comment]
I believe this is fixed by the latest release, but I need to add a test.

**Comment by knownasilya** [comment]
Fixed.

**Comment by knownasilya** [comment]
Can be closed
